services:
  node-backend:
    build:
      context: ./
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      RP_NETLOC: ${RP_NETLOC}
      RP_BASEPATH: ${RP_BASEPATH}
      RP_SCHEME: ${RP_SCHEME}
      BACKEND_PORT: ${BACKEND_PORT}
      OTEL_SERVICE_NAME: ${OTEL_SERVICE_NAME}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS}
      LOG_LEVEL: ${LOG_LEVEL}
